### PR TITLE
Project Using Bootstrap

### PR DESCRIPTION
**Pull request by Bekhzod96**
This project was built a replica of the news site Newsweek.com using the Bootstrap framework. Most parts of the project were created by using predefined Boostrap classes and only a few were added to make it page look like the same as the original.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey @Bekhzod96   :wave: 
## Good attempts on this one :muscle: :+1: 
But there are some very important things you have to consider before stepping ahead in the issues below :point_down: 
### :one: This page is a clone page from the [newsweek](https://www.newsweek.com/), therefore its section should contain the same order in the different screen sizes 
### :two: Most of the differents occure when resizing the page

## Here are the issues to address to get the project meet the requirement:wink:

#### Phone Resolution (Width: 375px)

---

## Header
- [ ] The Nav-Bar element aren't aligned
- [ ] Subscribe Button missing padding
- [ ] The section is too big
- [ ] The background color is diferent 
##### Required:
Screenshot from 2020-03-24 20-20-40
##### Yours: 
Screenshot from 2020-03-25 19-28-22

---

## :red_circle: :red_circle: :red_circle:  Most of your section is actually disorganize and make it very hard to compare it with the original before any other code review, be sure to check this issue  :red_circle: :red_circle: :red_circle:

---


## Footer Section
- [ ]  The footer doesn't display media-icons correctly
- [ ]  The footer element isn't aligned as the original page
- [ ]  The links items should not have the left bar
##### Required:
Screenshot from 2020-03-24 20-24-23
##### Yours: 
Screenshot from 2020-03-25 19-35-48

---

#### Pad Resolution (Width: 768px):

###### This resolution contains the same mistake as in the mobile resolution, be sure to compare it with the original if you need any further assistance don't hesitate to contact me through slack 

#### Max Resolution + (Width: 1024px):

#### Great Work Over Here! :muscle: 

there is quite a few things to check, as my college say before please do the fallowing issue before resubmiting

- [ ] Navbar should be wider and thinner

##### Required:
Screenshot from 2020-03-25 20-17-37
##### Yours: 
Screenshot from 2020-03-25 20-17-27

- [ ] The Newsweek is missing an image? 
##### Required:
Screenshot from 2020-03-25 20-16-15
##### Yours: 
Screenshot from 2020-03-25 20-16-27

- [ ] The Newsletter image is not well sized
 ##### Required:
Screenshot from 2020-03-25 20-17-06
##### Yours: 
Screenshot from 2020-03-25 20-17-17



## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by majovanilla** [comment]
Good job on this project! :+1: 

However, you haven't met some of the requirements made by the previous TSE's:

- [ ] The newsletter image still has the wrong size.
Screenshot from 2020-03-27 17-03-20

- [ ] You still have the blue tag on the images of the in the Magazine:
Screenshot from 2020-03-27 17-04-25

- [ ] Your opinion section still has images too large.
Screenshot from 2020-03-27 17-04-35

- [ ] **Optional** Check your hover effects. It should be underlined in red, not black.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by thsvr** [comment]
STATUS: PROJECT APPROVED :1st_place_medal: :1st_place_medal: :1st_place_medal: 

Hi @Bekhzod96  :smile_cat: 

**Congrats for the hard work, your project was approved** :fireworks: :fireworks: :fireworks: 

There is no blue button on the original page, can you please fix it on your project before merging the branch features into master? No need to ask for another review, I trust you guys will do this simple fix before merge it :smile: 

### Optional Suggestions for the next project:

:v:  You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''newsweek-page'' instead of ''feature", for example. It will be more descriptive. :smile_cat: 

If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project** :computer: 

Project reviewed by Thaís Vieira (TSE)

**Pull request merged**
